CREATE TABLE [dbo].[Countries]
(
	[ID]			INT					NOT NULL IDENTITY(1, 1),
	[GuidID]		UNIQUEIDENTIFIER	NOT NULL,
	[Name]			VARCHAR(100)		NOT NULL,
	[Active]		BIT					CONSTRAINT [DF_Country_Active]		DEFAULT (1) NOT NULL,
	[Deleted]		BIT					CONSTRAINT [DF_Country_Deleted]		DEFAULT (0) NOT NULL,
	[Created_at]	DATETIME			CONSTRAINT [DF_Country_Created_at]	DEFAULT (GETDATE()) NOT NULL

	CONSTRAINT [PK_Countries] PRIMARY KEY CLUSTERED ([ID] ASC)
)
