CREATE TABLE [dbo].[UserRoles]
(
	[ID]		INT					NOT NULL IDENTITY(1, 1),
	[GuidID]	UNIQUEIDENTIFIER	NOT NULL,
	[Code]		VARCHAR(50)			NOT NULL,
	[Name]		VARCHAR(100)		NOT NULL,
	[Active]	BIT					CONSTRAINT [DF_UserRole_Active]		DEFAULT (1) NOT NULL,
	[Deleted]	BIT					CONSTRAINT [DF_UserRole_Deleted]	DEFAULT (0) NOT NULL

	CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([ID] ASC)
)
