CREATE TABLE [dbo].[UserRoles]
(
	[ID]		UNIQUEIDENTIFIER	NOT NULL,
	[Name]		VARCHAR(100)		NOT NULL,
	[Active]	BIT					CONSTRAINT [DF_UserRole_Active]		DEFAULT (1) NOT NULL,
	[Deleted]	BIT					CONSTRAINT [DF_UserRole_Deleted]	DEFAULT (0) NOT NULL

	CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([ID] ASC)
)
